title: Ahrar Bin Aslam
logo: /assets/img/profile-pic (1).png
description: >
  I am a student of masters in Cybersecurity at Saarland University. I completed my Bachelors in Telecommunications Engineering 
  from Mehran University, Jamshoro, by securing the first position in my batch. I have conducted research in natural language 
  processing, artificial intelligence, and 6G networks. You can contact me via email or LinkedIn, I sometimes write on 
  [Medium](https://medium.com/@ahrarbaslam23) as well.

theme: jekyll-theme-minimal
