title: Ahrar Bin Aslam's Portfolio
email: your-email@example.com
description: > # this means to ignore newlines until "baseurl:"
  My personal portfolio showcasing my work, certifications, and skills.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ahrarbinaslam.github.io" # the base hostname & protocol for your site
github_username: ahrarbinaslam

theme: jekyll-theme-minimal  # or your preferred Jekyll theme

# Build settings
markdown: kramdown

# Navigation links
nav_links:
  - name: "Home"
    link: "/"
  - name: "About"
    link: "/about"
  - name: "Teaching"
    link: "/teaching"
  - name: "Certifications"
    link: "/certifications"
  - name: "Education"
    link: "/education"
  - name: "Work Experience"
    link: "/experience"
  - name: "Skills"
    link: "/skills"
  - name: "Projects"
    link: "/projects"
  - name: "Contact"
    link: "/contact"
