title: Ahrar Bin Aslam
logo: /assets/img/profile-pic (1).png
description: >
  I am a masters student of Cybersecurity at Saarland University. I completed my Bachelors in Telecommunications Engineering 
  from Mehran University, Jamshoro, by securing the first position in my batch. I have conducted research in natural language 
  processing, artificial intelligence, and 6G networks. You can contact me via email or LinkedIn.

theme: jekyll-theme-minimal
